AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloCppFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloCpp
      Handler: hello_cpp
      Runtime: provided
      MemorySize: 512
      CodeUri: build/products/Release/bin/
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET
    Metadata:
      BuildMethod: makefile